CREATE TABLE IF NOT EXISTS PUBLIC.USERS (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(255) NOT NULL,
    LOGIN VARCHAR(255) NOT NULL,
    NAME VARCHAR(255),
    BIRTHDAY DATE,
    CONSTRAINT PK_USERS PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FRIENDSHIP (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USER_ID INTEGER NOT NULL,
    FRIEND_ID INTEGER NOT NULL,
    STATUS VARCHAR(255),
    CONSTRAINT PK_FRIENDSHIP PRIMARY KEY (ID),
    CONSTRAINT FK_FRIENDSHIP_USER FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_FRIENDSHIP_FRIEND FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PUBLIC.RATING (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    RATING_CODE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    CONSTRAINT PK_RATING PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILM (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    RELEASE_DATE DATE NOT NULL,
    DURATION INTEGER,
    RATING_ID INTEGER,
    CONSTRAINT PK_FILM PRIMARY KEY (ID),
    CONSTRAINT FK_FILM_RATING FOREIGN KEY (RATING_ID) REFERENCES PUBLIC.RATING(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PUBLIC.GENRE (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CONSTRAINT PK_GENRE PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.FILMGENRE (
    FILM_ID INTEGER NOT NULL,
    GENRE_ID INTEGER NOT NULL,
    CONSTRAINT PK_FILMGENRE PRIMARY KEY (FILM_ID, GENRE_ID),
    CONSTRAINT FK_FILMGENRE_FILM FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILM(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_FILMGENRE_GENRE FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC.GENRE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PUBLIC.LIKES (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USER_ID INTEGER NOT NULL,
    FILM_ID INTEGER NOT NULL,
    CONSTRAINT PK_LIKES PRIMARY KEY (ID),
    CONSTRAINT FK_LIKES_USER FOREIGN KEY (USER_ID) REFERENCES PUBLIC.USERS(ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT FK_LIKES_FILM FOREIGN KEY (FILM_ID) REFERENCES PUBLIC.FILM(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);